name: e2e tests

on:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.MACHINE_USER_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout pull request HEAD commit instead of merge commit - needed to get correct Docker tag commit SHA
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies (python)
        run: |
          pip install -r requirements.lock
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag Docker image with latest commit hash
      - name: Set Docker tag
        id: set_docker_tag
        run: echo "DOCKER_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build docker images
        run: make tag=$DOCKER_TAG build

      - name: Publish docker images
        run: make publish

#      - name: Run e2e node tests on monorepo
#        run: gh workflow run infernet_node_tests.yaml -R ritual-net/infernet-monorepo-internal --ref main -f docker-tag=$DOCKER_TAG
#
#      - name: Run e2e service tests on monorepo
#        run: gh workflow run infernet_services_tests.yaml -R ritual-net/infernet-monorepo-internal --ref main -f docker-tag=$DOCKER_TAG

      - name: Run e2e node tests on monorepo
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ritual-net
          repo: infernet-monorepo-internal
          github_token: ${{ secrets.MACHINE_USER_PAT }}
          github_user: gh-deployer-01
          workflow_file_name: infernet_node_tests.yaml
          ref: main
          wait_interval: 10
          client_payload: '{"docker-tag":"${{ env.DOCKER_TAG }}"}'
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true


      - name: Download Docker Hub CLI
        run: wget https://github.com/docker/hub-tool/releases/download/v0.4.6/hub-tool-linux-amd64.tar.gz

      - name: Untar Docker Hub CLI
        run: tar -xvzf hub-tool-linux-amd64.tar.gz

      # automates auto login to Dock Hub CLI
      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Auto login to Docker Hub CLI
        run: ./docker-hub.exp

      # give enough time for the image to be pulled down so it's not needed anymore
      - name: Sleep for 1 minute
        run: sleep 60s

      - name: Delete docker image from Docker Hub
        run: ./hub-tool/hub-tool tag rm ritualnetwork/infernet-node:$DOCKER_TAG -f

#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1

#      - name: Cleanup Docker image
#        if: always()
#        run: docker rmi my-image:latest