name: e2e tests

on:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_TAG:     ${{ steps.set_docker_tag.outputs.DOCKER_TAG }}
      DOCKER_TAG_GPU: ${{ steps.set_docker_gpu_tag.outputs.DOCKER_TAG_GPU }}
    env:
      GH_TOKEN: ${{ secrets.MACHINE_USER_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout pull request HEAD commit instead of merge commit - needed to get correct Docker tag commit SHA
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies (python)
        run: |
          pip install -r requirements.lock
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag Docker image with latest commit hash
      - name: Set Docker tag
        id: set_docker_tag
        run: |
          DOCKER_TAG=$(git rev-parse --short HEAD)
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_OUTPUT

      - name: Set Docker GPU tag
        id: set_docker_gpu_tag
        run: |
          DOCKER_TAG_GPU=$DOCKER_TAG-gpu
          echo "DOCKER_TAG_GPU=$DOCKER_TAG_GPU" >> $GITHUB_ENV
          echo "DOCKER_TAG_GPU=$DOCKER_TAG_GPU" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: make tag=$DOCKER_TAG build

      - name: Build docker GPU image
        run: make tag=$DOCKER_TAG_GPU build-gpu

      - name: Publish docker image
        run: make tag=$DOCKER_TAG publish

      - name: Publish docker GPU image
        run: make tag=$DOCKER_TAG_GPU publish

  run-e2e:
    runs-on: ubuntu-latest
    needs: publish-docker-images
    outputs:
      DOCKER_TAG:     ${{ needs.publish-docker-images.outputs.DOCKER_TAG }}
      DOCKER_TAG_GPU: ${{ needs.publish-docker-images.outputs.DOCKER_TAG_GPU }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - workflow_file_name: infernet_node_tests.yaml
            docker_tag: ${{ needs.publish-docker-images.outputs.DOCKER_TAG }}
          - workflow_file_name: infernet_node_tests.yaml
            docker_tag: ${{ needs.publish-docker-images.outputs.DOCKER_TAG_GPU }}

    steps:
      - name: Run tests on monorepo (tag:${{ needs.publish-docker-images.outputs.DOCKER_TAG }})
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ritual-net
          repo: infernet-monorepo-internal
          github_token: ${{ secrets.MACHINE_USER_PAT }}
          github_user: ${{ secrets.MACHINE_USER }}
          workflow_file_name: ${{ matrix.workflow_file_name }}
          ref: main
          wait_interval: 30
          client_payload: '{"docker-tag":"${{ matrix.docker_tag }}"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

  delete-docker-images:
    runs-on: ubuntu-latest
    needs: run-e2e
    if: always()
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Download Docker Hub CLI
        run: wget https://github.com/docker/hub-tool/releases/download/v0.4.6/hub-tool-linux-amd64.tar.gz

      - name: Untar Docker Hub CLI
        run: tar -xvzf hub-tool-linux-amd64.tar.gz

      # automates auto login to Docker Hub CLI
      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Auto login to Docker Hub CLI
        run: ./docker-hub.exp

      - name: Delete docker image from Docker Hub
        run: ./hub-tool/hub-tool tag rm ritualnetwork/infernet-node:${{ needs.run-e2e.outputs.DOCKER_TAG }} -f

      - name: Delete docker GPU image from Docker Hub
        run: ./hub-tool/hub-tool tag rm ritualnetwork/infernet-node:${{ needs.run-e2e.outputs.DOCKER_TAG_GPU }} -f
